version: '3.8'

# // -H 0.0.0.0

services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://backend:4000
      PORT: 3000
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.backend
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: zurich
      DB_PASSWORD: 'QPalABSijLwc2tt9NEHqPJV9m07iNU5d69THSNb1GCw='
      DB_DATABASE: CUSTOMER_BILLING_PORTAL
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: zurich
      POSTGRES_PASSWORD: 'QPalABSijLwc2tt9NEHqPJV9m07iNU5d69THSNb1GCw='
      POSTGRES_DB: CUSTOMER_BILLING_PORTAL
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
